[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'vimClojure'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'jpalardy/vim-slime'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'open-browser.vim'

[[plugins]]
repo = 'tell-k/vim-browserreload-mac'


[[plugins]]
repo = 'tailchouchou2/html5.vim'

[[plugins]]
repo = 'kevinw/pyflakes-vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

# あまりつかわない？

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

# よくわからない

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

